id: eb8936425b0d40fbb3c7340708c113ea
initial_creation_type: ocr
source_metadata:
  volumes:
    cad8715120fd4c7c98af449c3d713f70:
      base_file: v064.txt
      image_group_id: I1PD95910
      title: མདོ་ཀུན་ལས་བཏུས་པ་ཆེན་པོ།
      total_pages: 1498
      volume_number: 65
